services:
  rag_server:
    build:
      context: ./RAG
      dockerfile: Dockerfile.rag
    ports:
      - "8000:8000"
    volumes:
      - ./RAG:/app
      - ./RAG/knowledge:/app/knowledge
      - ./Client:/app/Client
    environment:
      OLLAMA_URL: http://ollama:11434
    networks:
      - chatbot_network

  rasa_server:
    build:
      context: ./RASA
      dockerfile: Dockerfile.rasa
    ports:
      - "5005:5005"
    depends_on:
      - rasa_actions
    volumes:
      - ./RASA:/app
      - rasa_models:/app/models  

    command: rasa run --enable-api --cors "*" --debug
    networks:
      - chatbot_network

  rasa_actions:
    build:
      context: ./RASA
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
    volumes:
      - ./RASA/actions:/app/actions
    networks:
      - chatbot_network

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
    networks:
      - chatbot_network
    volumes:
      - ./client:/usr/share/nginx/html

  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"  # Ollama API port
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   restart: unless-stopped
  #   command: serve
  #   networks:
  #     - chatbot_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: navi-bot
    volumes:
      - db_data:/var/lib/mysql               
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - chatbot_network

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.31.5
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      CLUSTER_HOSTNAME: 'node1'
    networks:
      - chatbot_network

  smol:
    build:
      context: ./smol
      dockerfile: Dockerfile.smol
    container_name: smollm3
    ports:
      - "8500:8500"
    volumes:
      - ./smol:/app
      - ./RAG/knowledge/raw:/app/knowledge/raw
      - ./RAG/knowledge/txt:/app/knowledge/txt
      - ./RAG/knowledge/Json:/app/knowledge/Json
      - ~/.cache/huggingface:/root/.cache/huggingface #persists the checkpoint, saves time
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia



volumes:
  #ollama_data:
  db_data:
  rasa_models:
  weaviate_data:

networks:
  chatbot_network:
    external: true
