FROM python:3.9.23

USER root
ENV HOME=/root
WORKDIR /app

# Poppler-utils is required for PDF processing
# Tesseract is required for OCR processing
RUN apt-get update && \
    apt-get install -y poppler-utils tesseract-ocr && \
    apt-get clean

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
RUN pip install pymysql
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple torch==2.7.1


COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]