FROM python:3.9-slim as builder
# Set up environment
ENV HOME=/root
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    poppler-utils \
    libgl1 libglib2.0-0 \
    build-essential \
    cmake \
    libpoppler-cpp-dev \
    pkg-config \
    python3-dev \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip wheel --no-cache-dir -r requirements.txt --wheel-dir /wheels &&\
    ls -la /wheels &&\
    echo "Wheels built successfully."

FROM python:3.9-slim as runtime
ENV home=/root
WORKDIR /app
#install only runtime sys deps
RUN apt-get update && apt-get install -y \
    poppler-utils \
    libgl1 libglib2.0-0 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

#copy pre-built Python wheels
COPY --from=builder /wheels /wheels
RUN pip install --no-cache-dir /wheels/* && rm -rf /wheels

# Copy app files
COPY . .

CMD ["python","-u","-m","uvicorn", "donut_api:app", "--host", "0.0.0.0", "--port", "8600"]