FROM python:3.9-slim

# Set up environment
ENV HOME=/root
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    poppler-utils \
    tesseract-ocr \
    libgl1 \
    libglib2.0-0 \
    build-essential \
    cmake \
    libpoppler-cpp-dev \
    pkg-config \
    python3-dev \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copy app files
COPY . .

CMD ["uvicorn", "donut_api:app", "--host", "0.0.0.0", "--port", "8600"]